In [2]:
# from mylab import *
from deepar.dataset.time_series import MockTs
from deepar.model.lstm import DeepAR


%matplotlib inline
from numpy.random import normal
import tqdm
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


# original test code

In [20]:
np.arange(0., n_steps + 1) * 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [25]:
batch_size = 2
n_steps = 20
t0 = np.random.rand(batch_size, 1) * (30- 0 - n_steps * 0.1)  # t0 size (batch_size, 1)
Ts = t0 + np.arange(0., n_steps + 1) * 0.1
# print(t0)
print(Ts)
print(Ts.shape)
a = Ts[:, :-1].reshape(-1, n_steps, 1)
# b = Ts[:, 1:].reshape(-1, n_steps, 1)
print(a.shape)

[[25.43989073 25.53989073 25.63989073 25.73989073 25.83989073 25.93989073
  26.03989073 26.13989073 26.23989073 26.33989073 26.43989073 26.53989073
  26.63989073 26.73989073 26.83989073 26.93989073 27.03989073 27.13989073
  27.23989073 27.33989073 27.43989073]
 [22.06735638 22.16735638 22.26735638 22.36735638 22.46735638 22.56735638
  22.66735638 22.76735638 22.86735638 22.96735638 23.06735638 23.16735638
  23.26735638 23.36735638 23.46735638 23.56735638 23.66735638 23.76735638
  23.86735638 23.96735638 24.06735638]]
(2, 21)
(2, 20, 1)


In [22]:
(Ts).shape

(1, 21)

In [3]:
# load data and define model
ts = MockTs()
dp_model = DeepAR(ts, epochs=50)
dp_model.instantiate_and_fit()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Epoch 1/50
50/50 [==============================] - ETA: 40s - loss: 11.353 - ETA: 8s - loss: 15.646 - ETA: 3s - loss: 14.18 - ETA: 2s - loss: 13.09 - ETA: 1s - loss: 13.92 - ETA: 1s - loss: 12.76 - ETA: 0s - loss: 12.34 - ETA: 0s - loss: 12.37 - ETA: 0s - loss: 12.06 - 1s 26ms/step - loss: 12.2602
Epoch 2/50
50/50 [==============================] - ETA: 0s - loss: 17.41 - ETA: 0s - loss: 14.06 - ETA: 0s - loss: 13.11 - ETA: 0s - loss: 12.87 - ETA: 0s - loss: 12.94 - ETA: 0s - loss: 12.63 - ETA: 0s - loss: 12.69 - ETA: 0s - loss: 12.48 - 0s 8ms/step - loss: 12.4493
Epoch 3/50
50/50 [==============================] - ETA: 0s - loss: 7.946 - ETA: 0s - loss: 12.78 - ETA: 0s - loss: 11.75 - ETA: 0s - loss: 11.58 - ETA: 0s - loss: 11.00 - ETA: 0s - loss: 11.33 - ETA: 0s - loss: 11.87 - ETA: 0s - loss: 12.01 - 0s 8ms/step - loss: 12.1525
Epoch 

50/50 [==============================] - ETA: 0s - loss: 6.112 - ETA: 0s - loss: 5.562 - ETA: 0s - loss: 5.687 - ETA: 0s - loss: 5.795 - ETA: 0s - loss: 5.767 - ETA: 0s - loss: 5.879 - ETA: 0s - loss: 5.911 - 0s 7ms/step - loss: 5.9019
Epoch 31/50
50/50 [==============================] - ETA: 0s - loss: 7.457 - ETA: 0s - loss: 6.227 - ETA: 0s - loss: 5.880 - ETA: 0s - loss: 5.945 - ETA: 0s - loss: 5.960 - ETA: 0s - loss: 5.852 - ETA: 0s - loss: 5.798 - 0s 7ms/step - loss: 5.8181
Epoch 32/50
50/50 [==============================] - ETA: 0s - loss: 5.097 - ETA: 0s - loss: 6.041 - ETA: 0s - loss: 6.065 - ETA: 0s - loss: 6.097 - ETA: 0s - loss: 5.949 - ETA: 0s - loss: 5.904 - ETA: 0s - loss: 5.893 - 0s 7ms/step - loss: 5.9107
Epoch 33/50
50/50 [==============================] - ETA: 0s - loss: 5.107 - ETA: 0s - loss: 5.645 - ETA: 0s - loss: 5.557 - ETA: 0s - loss: 5.550 - ETA: 0s - loss: 5.758 - ETA: 0s - loss: 5.677 - ETA: 0s - loss: 5.779 - 0s 7ms/step - loss: 5.7589
Epoch 34/50
50/50 [=

In [4]:
def get_sample_prediction(sample, fn):
    sample = np.array(sample).reshape(1, 20, 1)
    output = fn([sample])
    samples = []
    for mu,sigma in zip(output[0].reshape(20), output[1].reshape(20)):
        # normal generate a random number(float), which is Gaussian distrubution
        samples.append(normal(loc=mu, scale=np.sqrt(sigma), size=1)[0])
    return np.array(samples)

In [14]:
(a[0]).shape

(1, 20, 1)

In [17]:
(a[1]).shape

(1, 20, 1)

In [18]:
a[1]

array([[[ 1.02528007],
        [ 0.97893335],
        [ 0.89675491],
        [ 0.78246599],
        [ 0.64111027],
        [ 0.47885248],
        [ 0.30273235],
        [ 0.12038362],
        [-0.06027059],
        [-0.23133408],
        [-0.38525271],
        [-0.51511598],
        [-0.61493299],
        [-0.67987169],
        [-0.70645205],
        [-0.69268525],
        [-0.63815356],
        [-0.54402744],
        [-0.41301954],
        [-0.2492771 ]]])

In [12]:
a[0]

array([[[ 1.0335448 ],
        [ 1.02528007],
        [ 0.97893335],
        [ 0.89675491],
        [ 0.78246599],
        [ 0.64111027],
        [ 0.47885248],
        [ 0.30273235],
        [ 0.12038362],
        [-0.06027059],
        [-0.23133408],
        [-0.38525271],
        [-0.51511598],
        [-0.61493299],
        [-0.67987169],
        [-0.70645205],
        [-0.69268525],
        [-0.63815356],
        [-0.54402744],
        [-0.41301954]]])

In [6]:
a = ts.next_batch(1, 20)

In [7]:
# next_batch(self, batch_size, n_steps,target_var='target', verbose=False, padding_value=0) 
# ---> return a tuple X (feature space), y
# X = ( batch_size, n_steps, -1 )
batch = ts.next_batch(1, 20)  # next_batch(self, batch_size, n_steps):

ress = []
# tqdm 只是产生一个进度条
for i in tqdm.tqdm(range(300)):
    # predict_theta_from_input : 每次预测产生模型（高斯模型）的参数【均值，方差】数据, which is the optimal parameter value of Gaussion
    # get_sample_prediction : 得到预测值，进去多少个就产生多少个
    # get_sample_prediction 过程中并不会继续改变模型参数（即没有在训练），所以其实这个重复产生theta的过程是多余的
    ress.append(get_sample_prediction(batch[0], dp_model.predict_theta_from_input))

res_df = pd.DataFrame(ress).T
tot_res = res_df

plt.plot(batch[1].reshape(20), linewidth=6)
tot_res['mu'] = tot_res.apply(lambda x: np.mean(x), axis=1)
tot_res['upper'] = tot_res.apply(lambda x: np.mean(x) + np.std(x), axis=1)
tot_res['lower'] = tot_res.apply(lambda x: np.mean(x) - np.std(x), axis=1)
tot_res['two_upper'] = tot_res.apply(lambda x: np.mean(x) + 2*np.std(x), axis=1)
tot_res['two_lower'] = tot_res.apply(lambda x: np.mean(x) - 2*np.std(x), axis=1)

plt.plot(tot_res.mu, 'bo')
plt.plot(tot_res.mu, linewidth=2)
plt.legend("real","predeict")
plt.fill_between(x = tot_res.index, y1=tot_res.lower, y2=tot_res.upper, alpha=0.5)
plt.fill_between(x = tot_res.index, y1=tot_res.two_lower, y2=tot_res.two_upper, alpha=0.5)
plt.title('Prediction uncertainty')

KeyError: None

# test

In [5]:
l = []
for i in range(400):
    y = 1.005**i+np.random.standard_normal()*0.3
    l.append(y) 
ts = pd.DataFrame(l,columns=["target"])
ts.head()

target
0  0.792360
1  0.520205
2  0.934503
3  0.972906
4  0.373318

In [6]:
from deepar.dataset.time_series import TimeSeries
# load data and define model
# TimeSeries(self, pandas_df, one_hot_root_list=None, grouping_variable='category', scaler=None)
ts = TimeSeries(ts, grouping_variable = None)
dp_model = DeepAR(ts, epochs=50)
dp_model.instantiate_and_fit()

Epoch 1/50


KeyError: None

In [ ]:
def get_sample_prediction(sample, fn):
    sample = np.array(sample).reshape(1, 20, 1)
    output = fn([sample])
    samples = []
    for mu,sigma in zip(output[0].reshape(20), output[1].reshape(20)):
        # normal generate a random number(float), which is Gaussian distrubution
        samples.append(normal(loc=mu, scale=np.sqrt(sigma), size=1)[0])
    return np.array(samples)

In [ ]:
# next_batch(self, batch_size, n_steps,target_var='target', verbose=False, padding_value=0) 
# ---> return a tuple X (feature space), y
# X = ( batch_size, n_steps, -1 )
batch = ts.next_batch(1, 20)

ress = []
# tqdm 只是产生一个进度条
for i in tqdm.tqdm(range(300)):
    # predict_theta_from_input : 每次预测产生模型（高斯模型）的参数【均值，方差】数据, which is the optimal parameter value of Gaussion
    # get_sample_prediction : 得到预测值，进去多少个就产生多少个
    # get_sample_prediction 过程中并不会继续改变模型参数（即没有在训练），所以其实这个重复产生theta的过程是多余的
    ress.append(get_sample_prediction(batch[0], dp_model.predict_theta_from_input))

res_df = pd.DataFrame(ress).T
tot_res = res_df

plt.plot(batch[1].reshape(20), linewidth=6)
tot_res['mu'] = tot_res.apply(lambda x: np.mean(x), axis=1)
tot_res['upper'] = tot_res.apply(lambda x: np.mean(x) + np.std(x), axis=1)
tot_res['lower'] = tot_res.apply(lambda x: np.mean(x) - np.std(x), axis=1)
tot_res['two_upper'] = tot_res.apply(lambda x: np.mean(x) + 2*np.std(x), axis=1)
tot_res['two_lower'] = tot_res.apply(lambda x: np.mean(x) - 2*np.std(x), axis=1)

plt.plot(tot_res.mu, 'bo')
plt.plot(tot_res.mu, linewidth=2)
plt.fill_between(x = tot_res.index, y1=tot_res.lower, y2=tot_res.upper, alpha=0.5)
plt.fill_between(x = tot_res.index, y1=tot_res.two_lower, y2=tot_res.two_upper, alpha=0.5)
plt.title('Prediction uncertainty')